-- Filmek
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('Amerika Kapitány: Az elso bosszúálló', 'Captain America: The First Avenger', 2011, 'Javában dúl a második világháború 1941-ben. A lelkes és mindenre elszánt ifjú, Steve Rogers is jelentkezik a hadseregbe, ám a gyenge fizikuma miatt kiszuperálják a sorozáson. Ezért örömmel jelentkezik a titkos katonai kísérleti programba, az Újjászületés nevet viselo projektbe, melynek keretében szuperkatonát csinálnak belole. Az izomkolosszussá fejlodött Amerika kapitány feladata megállítani a nácik titkos tudománmyos részlegét, a Hydrát, melyet a világuralmi törekvéseket dédelgeto, rettegett Vörös Koponya vezet.', 1, 1, 6.9, 124);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('Marvel Kapitány', 'Captain Marvel', 2019, 'A Marvel Studios az 1990-es években játszódó filmje, a Marvel Kapitány egy teljesen új kaland a Marvel mozis univerzumának eddig nem ismert periódusából, amely Carol Danverst követi nyomon. Mikor egy két idegen faj közötti galaktikus háború eléri a Földet, Danvers néhány szövetségessel együtt az események forgatagában találja magát, s hamarosan a világegyetem egyik legerosebb hosévé válik.', 1, 2, 7.0, 123);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('Vasember', 'Iron Man', 2008, 'Tony Stark, a zseniális feltaláló és különc milliárdos éppen legújabb szuperfegyverét mutatja be, amikor a csoportot támadás éri és Tony mellkasába vasszilánk fúródik, mely lassan halad a szíve felé. Ráadásul foglyul ejtik és azt követelik tole, hogy építsen meg egy minden eddiginél pusztítóbb fegyvert. Tony meg is építi, azonban egy olyan páncélöltözet formájában, amely segítségére lehet a szökésben és távol tartja a vasszilánkot a szívétol. Így születik meg a legendás Vasember.', 1, 3, 7.9, 126);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('A hihetetlen Hulk', 'The Incredible Hulk', 2008, 'Bruce Banner, a tudós kétségbeesetten keresi a gyógymódot arra a gamma-sugárzásra, amely megmérgezte a sejtjeit, és egy fékezhetetlen haragú erot szabadít fel benne: a Hulkot. Banner kénytelen az árnyékba húzódni, bujkálni, elszakadni attól az élettol, amit ismert, és attól a notol, akit szeretett, miközben menekül az ot üldözo "Villám" Ross tábornok és a hadigépezet elol, akik azért üldözik, hogy elkapják, és erejét brutálisan kihasználják. Emellett azonban feltunik a színen egy új, szörnyu ellenfél, a Förtelem, akinek pusztító ereje még Hulkét is felülmúlja. Hosünknek tehát döntenie kell: vagy elfogadja a tudós békés életét, vagy felfedezi a host abban a lényben, aki benne lakozik.', 1, 4, 679, 112);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('Vasember 2', 'Iron Man 2', 2010, 'Kiderült, hogy a szuperhos Vasember valójában Tony Stark. Kihasználva az iránta való érdeklodést a milliárdos feltaláló fel akarja hívni a figyelmet a közjó szolgálatába állítható technikai újdonságokra. A kormány azonban azt szeretné, ha fejlesztéseit a hadsereg kapná. Tony azonban nem akarja megosztani a Vasemberrel kapcsolatos információit, attól fél, hogy azok rossz kezekbe kerülnek. Közben felbukkan egy rejtélyes figura a Stark család múltjából. Ivan Vanko a saját fegyverével akarja elpusztítani a Vasembert. A szuperhos kénytelen újra akcióba lépni, hogy a barátai segítségével legyozze azokat az eroket, amelyek ot és az emberiséget fenyegetik.', 1, 5, 7.0, 124);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('Thor', 'Thor', 2011, 'A hatalmas Thor rettenthetetlen harcos, óriási pörölyérol legendákat mesélnek. A csatában vitéz és legyozhetetlen, ám makacssága és hirtelen haragú természete nem teszi ot alkalmassá arra, hogy apját kövesse Ashgar trónján. Képtelen lenne megfontoltan irányítani birodalmát. Thor meggondolatlan tette miatt újra fellángol egy régi háború. Büntetésül a Földre számuzik, ahol kénytelen az emberek között élni. Amikor a világából érkezo gonosz le akarja igázni a Földet, Thornak el kell döntenie, melyik oldalra áll.', 1, 6, 7.0, 115);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('Bosszúállók', 'The Avengers', 2012, 'Nick Fury, a S.H.I.E.L.D. vezetoje új fenyegetést észlel. Az ellenfél minden eddiginél nagyobb veszélyt jelent a Földre. Fury a katasztrófa elkerülésére összehívja a szuperhosöket. A toborzás eredményeként hamarosan sohasem látott szupercsapat néz farkasszemet az ellenséggel. Vasember, Amerika kapitány, a Fekete Özvegy és a többiek indulnak harcba, hogy megakadályozzák bolygónk pusztulását. Bruce Banner megfékezhetetlen alteregója, Hulk azonban kis híján mindent szétrombol.', 1, 7, 8.0, 143);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('Vasember 3', 'Iron Man 3', 2013, 'A legutóbbi küldetése után Tony Stark talonba tette a Vasembert. A tudós-szuperhos boldogan él egykori asszisztensével, ám álmatlanságban szenved, és pánikrohamok gyötrik. Amikor merényletek sora rázza meg a várost, Stark úgy dönt, hogy felveszi a (vas)kesztyut, és szembeszáll a titokzatos ellenséggel. A Vasemberen végzett legújabb fejlesztése azonban még nem tökéletes, ráadásul felbukkan néhány korábbi ismerose is. Az ösztönei és a találékonysága segítségével talán sikerül felülemelkedni a nehézségeken.', 2, 8, 7.2, 130);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('Thor: Sötét világ', 'Thor: The Dark World', 2013, 'Amikor a Föld és a Kilenc Birodalom világa fedésbe kerül, megnyílnak a bolygók közötti dimenziókapuk. Ezt kihasználva akar mindent elpusztítani Malekith, a sötét elf, hogy visszataszítsa az univerzumot a teremtés elotti sötétségbe. Még Odin és Asgard sem tud szembeszállni azzal az ellenséggel, akivel Thornak szembe kell néznie. Veszélyes küldetése során újra találkozik szerelmével, az atomfizikus Jane Fosterrel, és ki kell szabadítania a börtönben sínylodo Lokit, hogy a segítségével visszaállítsa az univerzum rendjét.', 2, 9, 6.9, 112);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('Amerika Kapitány: A tél katonája', 'Captain America: The Winter Soldier', 2014, 'Két évvel a New Yorkért folytatott csata után Amerika kapitány, azaz Steve Rogers Washingtonban él, és próbál alkalmazkodni a modern világ kihívásaihoz. Amikor azonban a S.H.I.E.L.D. egyik munkatársát megtámadják, a világot fenyegeto összeesküvés közepén találja magát. Szövetségesével, a Fekete Özveggyel együtt ered az igazság nyomába, miközben bérgyilkosok hada próbálja elkapni oket. Hamarosan csatlakozik hozzájuk Sólyom is, ám így is minden erejükre szükség lesz, hogy leszámoljanak ellenfelükkel.', 2, 10, 7.8, 136);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('A galaxis orzoi', 'Guardians of the Galaxy', 2014, 'A kalandor Peter Quill ellopja a titokzatos gömböt, amelyre a bolygóközi uralomra töro Ronan is pályázik. A fogonosz ezért hajtóvadászatot indít utána. Menekülés közben Quill kényszeru szövetséget köt négy különös alakkal: Rockettel, Groottal, Gamorával és Draxszal. Az állig felfegyverzett mosómedve, az élo fára emlékezteto lény, a veszedelmes bérgyilkosno és a Pusztító alkotják a Galaxis orzoit. Quill rájön, hogy a titokzatos gömbnek milyen ereje van, és mekkora veszélyt jelent az univerzumra nézve.', 2, 11, 8.0, 121);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('A galaxis orzoi Vol. 2', 'Guardians of the Galaxy Vol. 2', 2017, 'Miközben szól a Király Válogatáskazi #2, a Marvel produkciójában készült A galaxis orzoi Vol. 2.-ben folytatódnak a csapat kalandjai, melyek a kozmosz távolabbi szegleteibe vezetik oket. Az orzoknek sokat kell tenniük azért, hogy összetartsák újdonsült családjukat, miközben kiderítenek egyet s mást Peter Quill igazi szüleirol is.', 2, 12, 7.6, 136);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('Bosszúállók: Ultron kora', 'Avengers: Age of Ultron', 2015, 'Amikor Tony Stark újra életet akar lehelni a parkolópályára állított békefenntartó programba, nem minden sikerül a tervei szerint. A Föld legnagyobb hoseinek, vagyis Vasembernek, Amerika kapitánynak, Thornak, a Hihetetlen Hulknak, a Fekete Özvegynek és Sólyomszemnek ezúttal a legvégso megmérettetésen kell helytállniuk, mivel a bolygó sorsáról van szó. A rettegett Ultron megjelenésével a Bosszúállókra vár a feladat, hogy megakadályozzák ördögi terve megvalósítását. Az egyedülálló, globális kaland azonban csupán vonakodva megköttetett szövetségek és nem várt események árán teljesedhet ki.', 2, 13, 7.3, 141);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('A Hangya', 'Ant-Man', 2015, 'A Marvel Moziuniverzum következo epizódjában a nézok megismerkedhetnek az eredeti Bosszúállók egyik alapítójával, aki elso alkalommal látható a mozivásznon. A Hangya szuperképessége, hogy rendkívül kis méreture tud zsugorodni, miközben ereje megsokszorozódik. A Scott Lang polgári névre hallgató, rendkívül sikeres tolvaj sorsa úgy alakul, hogy akarva-akaratlanul hossé válik, amikor segítenie kell egykori mentorának, Dr. Hank Pymnek. A doktor által tervezett speciális Hangya páncélra gonosz erok vetettek szemet, a két férfinak ezért meg kell akadályozni, hogy a különleges öltözet rossz kezekbe kerüljön. Pymnek és Langnek ezért együtt kell dolgoznia, hogy végrehajtsák a tökéletes rablást és ezzel megmentsék a világot.', 2, 14, 7.3, 117);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('Amerika Kapitány: Polgárháború', 'Captain America: Civil War', 2016, 'Az Amerika kapitány: Polgárháborúban Steve Rogers az újjáalakult Bosszúállók csapatának élén próbál gondoskodni az emberiség biztonságáról. Azonban egy újabb incidens következik be, amelynek nem várt következményei lesznek. A Bosszúállókon egyre no a politikai nyomás, hogy egy kormányzati szerv irányítsa oket, akiknek be kell számolniuk akcióikról. Az új rend megosztja a Bosszúállókat, a csapat két részre szakad. Az egyik csoport élén Steve Rogers áll, aki úgy véli, a Bosszúállóknak szabadon kellene tevékenykednie, hogy védelmezhessék az emberiséget. A másik frakció élén Tony Star, aki az irányítás és elszámoltathatóság eszméjét támogatja. A nézoknek döntenie kell, hogy melyik tábornak drukkolnak, miközben a háború immár két fronton zajlik.', 3, 15, 7.8, 147);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('Fekete Párduc', 'Black Panther', 2018, 'A Marvel Studios Fekete Párduc címu új filmjének hose T\'Challa, aki apja halálát követoen hazatér az elszigetelt, ám technológiailag fejlett afrikai országba, Wakanda királyságába, hogy elfoglalja az ot megilleto helyet a trónon. Ám mikor egy nagy hatalmú osi ellenség ismét feltunik a színen, T\'Challa királyként és a Fekete Párducként is próbára tétetik: a félelmetes összecsapás kimenetelén nem pusztán Wakanda, hanem az egész világ sorsa áll. Árulások és veszélyek közepette az ifjú uralkodónak maga mellé kell állítania szövetségeseit és felszínre kell engednie a Fekete Párduc minden erejét, hogy legyozze ellenfeleit és biztonságban tudhassa népét.', 3, 16, 7.3, 134);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('Pókember: Hazatérés', 'Spider-Man: Homecoming', 2017, 'Kamaszodni eleve nem könnyu, és Peter nem arról híres, hogy feltalálja magát. Nagyon vicces srác, mégsem tartozik a nagymenok közé. Nappal. Éjszaka azonban övé a nagyváros, és nemcsak utcaszinten. Különleges szerkóban lendül felhokarcolóról felhokarcolóra, nem lehet meglépni elole és nem könnyu legyozni. Eddig legalábbis senkinek sem sikerült.De a Pókember most egészen új ellenségekkel találkozik, és úgy tunik, még a szokásos humora is kevés lehet hozzá, hogy életben maradjon. Az új bajban új szövetségesek után kell néznie.', 3, 17, 7.4, 133);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('Doctor Strange', 'Doctor Strange', 2016, 'A világhíru idegsebész, Dr. Stephen Strange élete tragikus fordulatot vesz egy szörnyu autóbaleset következtében. Miután a kezeit attól kezdve használni képtelen orvosnak a hagyományos gyógymódok nem használnak, valószínutlen helyen talál segítséget - egy titokzatos himalájai enklávé, a Kamar-Taj az utolsó reménye. Strange hamarosan rádöbben, ez a hely nem pusztán a gyógyításé, hanem a hadviselésé is: láthatatlan, sötét eroket kell visszaverniük, melyek világunk elpusztítására törekszenek. A doktor rövidesen válaszút elé kerül: visszatér régi, vagyonnal és népszeruséggel járó életéhez, vagy hátat fordít múltjának és újonnan szerzett mágikus képességeit latba vetve a világ szolgálatába áll a valaha volt legerosebb mágusként.', 3, 18, 7.5, 115);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('Thor: Ragnarök', 'Thor: Ragnarok', 2017, 'A Marvel Studios új filmjében Thort pörölyétol megfosztva bebörtönzik az univerzum túlsó felén. Az idovel versenyt futva próbál visszajutni Asgardba, és megállítani a Ragnarököt; egy háborút, ami otthonának pusztulásával és az asgardi civilizáció eltunésével járhat, és amit egy mindenható új ellenség, a könyörtelen Hela idézett elo. Eloször azonban túl kell élnie egy halálos gladiátorviadalt, amelyben ellenfele korábbi szövetségese és szintén a Bosszúállók tagja: a hihetetlen Hulk!', 3, 19, 7.9, 130);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('A Hangya és a Darázs', 'Ant-Man and the Wasp', 2018, 'A Marvel Studios új filmjében az Amerika Kapitány: Polgárháború eseményeit követoen Scott Lang kénytelen viselni döntései következményeit szuperhosként és apaként egyaránt. Próbál egyensúlyozni a magánéletében és a Hangyaként reá nehezedo felelosséggel, ám mikor Hope van Dyne és Dr. Hank Pym felkeresi, újabb küldetésre indul. A Darázs személyében társat is kap, így csapatban derítenek fel súlyos titkokat a múltból.', 3, 20, 7.1, 118);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('Bosszúállók: Végtelen háború', 'Avengers: Infinity War', 2018, 'A Marvel mozis univerzumának egészét felölelo, tíz év eseményeinek tetopontját jelento Bosszúállók: Végtelen háborúban minden idok legnagyobb és leghalálosabb leszámolására kerül sor. A Bosszúállóknak és szövetségeseiknek mindent kockára kell tenniük, hogy megfékezzék a nagy ereju Thanost, aki egy szemvillanás alatt elpusztíthatja a világot.', 3, 21, 8.5, 149);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('Bosszúállók: Végjáték', 'Avengers: Endgame', 2019, 'Thanos súlyos tette, amivel elpusztította az univerzum élolényeinek felét és megtörte a Bosszúállókat, a megmaradt hosöket egy végso összecsapásra készteti a Marvel Studios huszonegy filmet megkoronázó, nagyszabású fináléjában, a Bosszúállók: Végjátékban.', 3, 22, 8.5, 181);
INSERT INTO MOVIE(title_hu, title_en, year, desc, phase, order_num, rate, length) VALUES('Pókember: Idegenben', 'Spider-Man: Far from Home', 2019, 'Pókember nem pihenhet. Az már kiderült, hogy az ifjú pók egyedül is képes megmenteni a világot, és csoportban is megállja a helyét, de közben o úgy érzi, hogy neki is jár mindaz, ami bármelyik középiskolásnak: és a haverjaival európai utazásra indul. De éppen, amikor végre élvezhetné mindazt, amit a baráti lazulás kínálhat, újabb kihívás elé kell néznie. A rejtélyes Mysterio miatt új kalandba indul, és könnyen lehet, hogy Pókember, aki nagy nehezen próbálja a hátizsákos utazást a hosi küzdelemmel összehangolni, kénytelen régi Bosszúálló társaitól segítséget kérni.', 3, 22, 7.7, 129);


-- Hosök
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Steven Grant Rogers', 'Amerika Kapitány', 'ember', 'Chris Evans');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('James Buchanan Barnes', 'Fehér Farkas', 'ember', 'Sebastian Stan');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Carol Danvers', 'Marvel Kapitány', 'ember / Kree hibrid', 'Brie Larson');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Nicholas Joseph Fury', 'Nick Fury', 'ember', 'Samuel L. Jackson');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Anthony Edward Stark', 'Vasember', 'ember', 'Robert Downey Jr.');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('James Rupert Rhodes', 'Hadigép', 'ember', 'Don Cheadle');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Robert Bruce Banner', 'Hulk', 'ember', 'Mark Ruffalo');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Thor Odinson', 'Thor', 'asgardi', 'Chris Hemsworth');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Natalia Alianovna Romanoff', 'Fekete Özvegy', 'ember', 'Scarlett Johansson');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Clinton Francis Barton', 'Sólyomszem', 'ember', 'Jeremy Renner');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Virginia Potts', 'Héra', 'ember', 'Gwyneth Paltrow');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Samuel Thomas Wilson', 'Sólyom', 'ember', 'Anthony Mackie');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Peter Jason Quill', 'Urlord', 'ember / Élo Bolygó hibrid', 'Chris Pratt');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Gamora', 'Gamora', 'Zehoberei', 'Zoe Saldana');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Drax', 'Drax a Pusztító', 'mutáns', 'Dave Bautista');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Groot', 'Groot', 'Flora colossus', 'Vin Diesel (hang)');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('89P13', 'Mordály', 'Halfworlder', 'Bradley Cooper (hang)');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Nebula', 'Nebula', 'Luphomoid', 'Karen Gillan');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Mantis', 'Mantis', 'Empata', 'Pom Klementieff');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Pietro Maximoff', 'Higanyszál', 'ember(telen)', 'Aaron Taylor-Johnson');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Wanda Maximoff', 'Skarlát Boszorkány', 'ember(telen)', 'Elizabeth Olsen');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Vízió', 'Vízió', 'Android', 'Paul Bettany');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Scott Edward Harris Lang', 'Hangya', 'ember', 'Paul Rudd');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Hope van Dyne', 'Darázs', 'ember', 'Evangeline Lilly');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('T\'Challa', 'Fekete Párduc', 'ember', 'Chadwick Boseman');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Okoye', 'Okoye', 'ember', 'Danai Gurira');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Shuri', 'Shuri', 'ember', 'Letitia Wright');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Peter Benjamin Parker', 'Pókember', 'ember', 'Tom Holland');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Stephen Vincent Strange', 'Doctor Strange', 'ember', 'Benedict Cumberbatch');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Wong', 'Wong', 'ember', 'Benedict Wong');
INSERT INTO HERO(name, alias, species, portrayed_by) VALUES('Brünhild', 'Valkur', 'asgardi', 'Tessa Thompson');


-- Termek
INSERT INTO ROOM(name, rows, seats) VALUES('New York', 5, 6);
INSERT INTO ROOM(name, rows, seats) VALUES('Wakanda', 5, 6);
INSERT INTO ROOM(name, rows, seats) VALUES('Sokovia', 5, 6);
INSERT INTO ROOM(name, rows, seats) VALUES('Titán', 5, 6);
INSERT INTO ROOM(name, rows, seats) VALUES('Asgard', 5, 6);
INSERT INTO ROOM(name, rows, seats) VALUES('Hala', 5, 6);
INSERT INTO ROOM(name, rows, seats) VALUES('Tudástér', 5, 6);
INSERT INTO ROOM(name, rows, seats) VALUES('Svartalfheim', 5, 6);
INSERT INTO ROOM(name, rows, seats) VALUES('Tønsberg', 5, 6);
INSERT INTO ROOM(name, rows, seats) VALUES('Kamar-Taj', 5, 6);


-- Vetítések
INSERT INTO PROJECTION(time) VALUES('2020-07-22T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-03-08T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-05-02T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-06-13T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-05-07T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-05-06T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-05-04T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-05-03T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-11-08T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-04-04T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-08-01T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-05-05T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-05-01T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-07-17T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-05-06T15:30:00');
INSERT INTO PROJECTION(time) VALUES('2020-02-16T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-07-07T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-11-04T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-11-03T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-07-06T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-04-26T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-04-27T10:00:00');
INSERT INTO PROJECTION(time) VALUES('2020-07-02T10:00:00');